
export default new Map([
["src/content/docs/ch01_oop/01_foundation_classes.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fch01_oop%2F01_foundation_classes.mdx&astroContentModuleFlag=true")],
["src/content/docs/ch01_oop/02_foundation_inheritance.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fch01_oop%2F02_foundation_inheritance.mdx&astroContentModuleFlag=true")],
["src/content/docs/ch01_oop/04_properties.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fch01_oop%2F04_properties.mdx&astroContentModuleFlag=true")],
["src/content/docs/ch01_oop/exercises.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fch01_oop%2Fexercises.mdx&astroContentModuleFlag=true")],
["src/content/docs/ch02_functional_programming/01_what_is_it.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fch02_functional_programming%2F01_what_is_it.mdx&astroContentModuleFlag=true")],
["src/content/docs/ch02_functional_programming/02_pure_functions.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fch02_functional_programming%2F02_pure_functions.mdx&astroContentModuleFlag=true")],
["src/content/docs/ch02_functional_programming/03_lambda_functions.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fch02_functional_programming%2F03_lambda_functions.mdx&astroContentModuleFlag=true")],
["src/content/docs/ch02_functional_programming/04_exercises.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fch02_functional_programming%2F04_exercises.mdx&astroContentModuleFlag=true")],
["src/content/docs/ch02_functional_programming/04_internals.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fch02_functional_programming%2F04_internals.mdx&astroContentModuleFlag=true")],
["src/content/docs/ch02_functional_programming/04_list_comprehensions.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fch02_functional_programming%2F04_list_comprehensions.mdx&astroContentModuleFlag=true")],
["src/content/docs/ch02_functional_programming/04_map_filter_reduce.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fch02_functional_programming%2F04_map_filter_reduce.mdx&astroContentModuleFlag=true")],
["src/content/docs/ch02_functional_programming/05_comprehensions.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fch02_functional_programming%2F05_comprehensions.mdx&astroContentModuleFlag=true")],
["src/content/docs/ch02_functional_programming/06_functional_toolkit.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fch02_functional_programming%2F06_functional_toolkit.mdx&astroContentModuleFlag=true")],
["src/content/docs/ch02_functional_programming/07_closures.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fch02_functional_programming%2F07_closures.mdx&astroContentModuleFlag=true")],
["src/content/docs/ch02_functional_programming/08_function_composition.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fch02_functional_programming%2F08_function_composition.mdx&astroContentModuleFlag=true")],
["src/content/docs/ch02_functional_programming/09_immutability_patterns.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fch02_functional_programming%2F09_immutability_patterns.mdx&astroContentModuleFlag=true")],
["src/content/docs/ch02_functional_programming/10_functional_iteration.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fch02_functional_programming%2F10_functional_iteration.mdx&astroContentModuleFlag=true")],
["src/content/docs/ch02_functional_programming/11_questions.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Fch02_functional_programming%2F11_questions.mdx&astroContentModuleFlag=true")],
["src/content/docs/index.mdx", () => import("astro:content-layer-deferred-module?astro%3Acontent-layer-deferred-module=&fileName=src%2Fcontent%2Fdocs%2Findex.mdx&astroContentModuleFlag=true")]]);
		